### ISSUE TITLE
Fencing-controller doesn't stop all pods

### ISSUE THREAD

**Issue by rustequal** [kvaps/kube-fencing#1]
Hello,

Thanks for the great project. It's simple and very useful.

We use it with k8s 1.12.3 and in our case we found a bug - The Fencing-controller doesn't stop all pods on the node.

There is a fragment from "fencing-controller.sh":

`      run kubectl get pod --field-selector "spec.nodeName=$1" --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name |
        awk '{if (!a[$1]++){printf "\n" $1 " " $2} else {printf " " $2}}' | tail -n+3 | head -n-1 |`

In our system this fragment return:

```
[root@k1 ~]# kubectl get pod --field-selector "spec.nodeName=k4" --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name
NAMESPACE        NAME
fencing          fencing-switcher-kv77t
kube-system      coredns-576cbf47c7-dfrx8
kube-system      kube-flannel-ds-amd64-p6m2b
kube-system      kube-proxy-nwrm4
metallb-system   speaker-8jw77
registry         registry-bcc9fd44b-zq7b2

[root@k1 ~]# kubectl get pod --field-selector "spec.nodeName=k4" --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name | awk '{if (!a[$1]++){printf "\n" $1 " " $2} else {printf " " $2}}' | tail -n+3 | head -n-1
fencing fencing-switcher-kv77t
kube-system coredns-576cbf47c7-dfrx8 kube-flannel-ds-amd64-p6m2b kube-proxy-nwrm4
metallb-system speaker-8jw77
```

As you see, the "registry" pod is lost.

We fixed this fragment of code in our system:

`      run kubectl get pod --field-selector "spec.nodeName=$1" --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name |
        awk '{if (!a[$1]++){printf "\n" $1 " " $2} else {printf " " $2}} END {print ""}' | tail -n+3 |
`

now it works fine:

```
[root@k1 ~]# kubectl get pod --field-selector "spec.nodeName=k4" --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name | awk '{if (!a[$1]++){printf "\n" $1 " " $2} else {printf " " $2}} END {print ""}' | tail -n+3
fencing fencing-switcher-kv77t
kube-system coredns-576cbf47c7-dfrx8 kube-flannel-ds-amd64-p6m2b kube-proxy-nwrm4
metallb-system speaker-8jw77
registry registry-bcc9fd44b-zq7b2
```

Best regards ;)

**Comment by kvaps** [comment]
Great fix, thanks for the report!
