### ISSUE TITLE
Keep the pod for the last fencing execution

### ISSUE THREAD

**Issue by jsalatiel** [kvaps/kube-fencing#12]
Would it be possible to keep the pod for the last fencing execution ( per node ) ? My after hook failed to be executed, but i have no access to the log because the pod was deleted after execution.  
I know the pod failed because I have not received the email and notification the after hook pod is supposed to send.

**Comment by kvaps** [comment]
Hey, usually pod should continue existing until node returned online.
Do you talk about that case?

**Comment by jsalatiel** [comment]
The node returned just fine, but the notifications were not send ( so afterhook pod somehow failed)


---
Case explained.
In my setup , my nodes should be fenced ater 30 seconds. So , to test if the fencing was working I SSH'ed to one of the nodes ( t est nodes of course ) and forced a crash by issuing 'echo c > /proc/sysrq-trigger'. That command will automatically reboot after doing some memory dump. While the server was still rebooting, the 30 seconds the fence controller expired and the fencing job was called and rebooted the server again ( I can see on vmware logs that it was fenced ). A few minutes later I can see the node was back online and according to the fence-controller log, the afterhook pod should also had been run. The problem is that the only thing that the afterhook pod does is send an email and notify me through telegram. I would like to see the the afterhook pod log, but since it was deleted I can not see it.

I will try to re-do the test soon.

**Comment by jsalatiel** [comment]
Not able to reproduce it anymore. Closing it.
