### ISSUE TITLE
helm chart for 2.1.0 does not match chart in the repository

### ISSUE THREAD

**Issue by ikorolev93** [kvaps/kube-fencing#14]
Git repo:

https://github.com/kvaps/kube-fencing/blob/07f50e9b0d3bc2a3ed88b8e8bc75119f71786bfc/deploy/helm/kube-fencing/templates/controller-rbac.yaml#L14-L15

Helm repo:

```sh
79d6cf78cab5:/tmp$ helm template kvaps/kube-fencing --version 2.1.0 | grep -A1 jobs
    resources: ["jobs"]
    verbs: ["list", "watch", "get", "create", "update", "patch"]
```

**Comment by kvaps** [comment]
Thanks for the report, fixed!

please run `helm repo update` before usage
