### ISSUE TITLE
Issue with Node Flip (node intermittently going to Not-Ready and then coming back to Ready state)

### ISSUE THREAD

**Issue by trishnendu** [kvaps/kube-fencing#21]
In this scenario, node is coming back to Ready state in between fencing operation. As node is back to Ready state, pods are getting started and getting deleted by the fencing flush operation afterwards. Is there anyways to abort the fencing operation if node comes back to Ready state? or anyways to prevent pods getting started in between fencing operation.

**Comment by kvaps** [comment]
Hi, yes, you can use `fencing/timeout` annotation

**Comment by trishnendu** [comment]
Thanks for the quick response. But timeout is not working in this case cause the time window of node flip is too random.

**Comment by kvaps** [comment]
Well, I usually set timeout 5-10 second, if node is not came back in this time, then it will be killed by fencing-controller.
There is no other option, sorry 🙂
